---
# Source: global-pull-secret-synch/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-config
  labels:
    helm.sh/chart: global-pull-secret-synch-0.1.0
    app.kubernetes.io/name: global-pull-secret-synch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  global-pull-secret-sync.sh: |
    #!/bin/bash

    while true
    do
      BLOCKLIST='["cloud.openshift.com","quay.io","registry.connect.redhat.com","registry.redhat.io"]'
      #echo "BLOCKLIST=$BLOCKLIST"
      echo "Synchronize docker config: $(date +"%T")"

      #ls -la /host
      #cat /host/.docker/config.json

      cp /host/.docker/config.json /host/.docker/config.json.backup

      oc extract secret/pull-secret \
        -n openshift-config

      jq -rc '.auths | keys[]' .dockerconfigjson | while read key; do

        #echo $key
        FOUND=$(echo "$BLOCKLIST" | jq -e '.[]|select(. == "'$key'")')

        # if not found in blocklist, then process the key
        if [ -z $FOUND ]; then
          echo "Processing \"$key\""

          VALUE=$(jq -cr ".auths.\"$key\"" .dockerconfigjson)

          cat /host/.docker/config.json | jq '.auths += {"'$key'":'$VALUE'}' > /host/.docker/config.json.tmp
          mv /host/.docker/config.json.tmp /host/.docker/config.json
        fi
      done

      rm -rf .dockerconfigjson

      sleep 5m
    done
---
# Source: global-pull-secret-synch/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-name-role
  labels:
    helm.sh/chart: global-pull-secret-synch-0.1.0
    app.kubernetes.io/name: global-pull-secret-synch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pull-secret"]
    verbs: ["*"]
---
# Source: global-pull-secret-synch/templates/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-rb
  labels:
    helm.sh/chart: global-pull-secret-synch-0.1.0
    app.kubernetes.io/name: global-pull-secret-synch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: global-pull-secret-synch-sa
    namespace: openshift-config
  - kind: ServiceAccount
    name: global-pull-secret-synch-sa
    namespace: tools
roleRef:
  kind: ClusterRole
  name: release-name-role
  apiGroup: rbac.authorization.k8s.io
---
# Source: global-pull-secret-synch/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-name-ds
  namespace: tools
  labels:
    helm.sh/chart: global-pull-secret-synch-0.1.0
    app.kubernetes.io/name: global-pull-secret-synch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: global-pull-secret-synch
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: global-pull-secret-synch-0.1.0
        app.kubernetes.io/name: global-pull-secret-synch
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: global-pull-secret-synch-sa
      securityContext:
        {}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scripts
          configMap:
            name: release-name-config
            defaultMode: 0777
        - hostPath:
            path: /
            type: Directory
          name: host
      containers:
        - name:  global-pull-secret-synch
          image: "quay.io/ibmgaragecloud/cli-tools:latest"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /host
              name: host
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /scripts/global-pull-secret-sync.sh
---
# Source: global-pull-secret-synch/charts/service-account/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tools
  name: global-pull-secret-synch-sa
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
  labels:
    helm.sh/chart: service-account-0.6.1
    app.kubernetes.io/name: global-pull-secret-synch-sa
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: global-pull-secret-synch/charts/service-account/templates/scc-privileged.yaml
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    argocd.argoproj.io/sync-options: Validate=false
    kubernetes.io/description: 'privileged allows access to all privileged and host
      features and the ability to run as any user, any group, any fsGroup, and with
      any SELinux context.  WARNING: this is the most relaxed SCC and should be used
      only for cluster administration. Grant with caution.'
  name: tools-global-pull-secret-synch-sa-privileged
  labels:
    helm.sh/chart: service-account-0.6.1
    app.kubernetes.io/name: global-pull-secret-synch-sa
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
  - '*'
allowedUnsafeSysctls:
  - '*'
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:cluster-admins
  - system:nodes
  - system:masters
priority: null
readOnlyRootFilesystem: false
requiredDropCapabilities: null
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
seccompProfiles:
  - '*'
supplementalGroups:
  type: RunAsAny
users:
  - system:serviceaccount:tools:global-pull-secret-synch-sa
volumes:
  - '*'