apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-role
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["pull-secret"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-rb
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "global-pull-secret-synch.serviceAccountName" . }}
    namespace: openshift-config
  - kind: ServiceAccount
    name: {{ include "global-pull-secret-synch.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io