apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "global-pull-secret-synch.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "global-pull-secret-synch.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "global-pull-secret-synch.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "global-pull-secret-synch.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: 60
      volumes:
        - name: scripts
          configMap:
            name: {{ .Release.Name }}-config
            defaultMode: 0777
        - hostPath:
            path: /
            type: Directory
          name: host
      containers:
        - name:  {{ .Chart.Name }}
          image: "quay.io/ibmgaragecloud/cli-tools:latest"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - mountPath: /scripts
              name: scripts
            - mountPath: /host
              name: host
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /scripts/global-pull-secret-sync.sh